## YAML Template.
Kpicaza\ExamBundle\Entity\QuestionResponse:
    type: entity
    repositoryClass: Kpicaza\ExamBundle\Entity\QuestionResponseRepository
    table: question_response
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
    manyToOne:
        question:
            targetEntity: Question
            joinColumn:
                name: question_id
                referencedColumnName: id
    manyToOne:
        answer:
            targetEntity: Answer
            joinColumn:
                name: answer_id
                referencedColumnName: id
