<?php

namespace Kpicaza\ExamBundle\Entity;

/**
 * ExamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * 
     * @param \DateTime $lastsync
     * @param type $limit
     * @param type $offset
     * @param type $keywords
     * @return type
     */
    public function findForRest(\DateTime $lastsync = null, $limit = null, $offset = null, $keywords = null)
    {
        $arr = array();

        $q = $this->findForRestQuery($lastsync, $limit, $offset, $keywords);

        return $q->getQuery()->getResult();
    }

    /**
     * 
     * @param \DateTime $lastsync
     * @param type $limit
     * @param type $offset
     * @param type $keywords
     * @return type
     */
    public function findForRestQuery(\DateTime $lastsync = null, $limit = null, $offset = null, $keywords = null)
    {

        $q = $this
            ->createQueryBuilder('c')
            ->select('c.id, c.subject, c.to_aprove, c.description')
        ;

        if (null !== $lastsync) {
            $query = '(c.created_at > :lastsync OR c.updated_at > :lastsync)';

            $q
                ->where($query)
                ->setParameter('lastsync', $lastsync)
            ;
        }

        if (null !== $keywords) {
            $q
                ->andWhere('c.subject LIKE :keywords OR c.description LIKE :keywords')
                ->setParameter('keywords', '%' . $keywords . '%')
            ;
        }

        if (null !== $limit && null !== $offset) {
            $q->setFirstResult($offset)->setMaxResults($limit);
        }

        return $q;
    }

}
