<?php

namespace Kpicaza\ExamBundle\Entity;

/**
 * ExamResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamResultRepository extends \Doctrine\ORM\EntityRepository
{
}
