<?php

namespace Kpicaza\ExamBundle\Entity;

/**
 * QuestionResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionResponseRepository extends \Doctrine\ORM\EntityRepository
{
}
