## YAML Template.
AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Entity\UserRepository
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }